# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Graph_editor(object):
    def setupUi(self, Graph_editor):
        Graph_editor.setObjectName("Graph_editor")
        Graph_editor.resize(831, 724)
        Graph_editor.setMinimumSize(QtCore.QSize(831, 724))
        Graph_editor.setMaximumSize(QtCore.QSize(831, 724))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lines.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        Graph_editor.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Graph_editor)
        self.widget.setGeometry(QtCore.QRect(10, 10, 815, 712))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBoxOwen = QtWidgets.QComboBox(self.widget)
        self.comboBoxOwen.setObjectName("comboBoxOwen")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.comboBoxOwen.addItem("")
        self.verticalLayout_5.addWidget(self.comboBoxOwen)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_27 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_2.addWidget(self.label_27)
        self.label_16 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_2.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_2.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.label_28 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEditTemp1 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp1.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp1.setObjectName("lineEditTemp1")
        self.verticalLayout_3.addWidget(self.lineEditTemp1)
        self.lineEditTemp2 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp2.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp2.setObjectName("lineEditTemp2")
        self.verticalLayout_3.addWidget(self.lineEditTemp2)
        self.lineEditTemp3 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp3.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp3.setObjectName("lineEditTemp3")
        self.verticalLayout_3.addWidget(self.lineEditTemp3)
        self.lineEditTemp4 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp4.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp4.setObjectName("lineEditTemp4")
        self.verticalLayout_3.addWidget(self.lineEditTemp4)
        self.lineEditTemp5 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp5.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp5.setObjectName("lineEditTemp5")
        self.verticalLayout_3.addWidget(self.lineEditTemp5)
        self.lineEditTemp6 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp6.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp6.setObjectName("lineEditTemp6")
        self.verticalLayout_3.addWidget(self.lineEditTemp6)
        self.lineEditTemp7 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp7.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp7.setObjectName("lineEditTemp7")
        self.verticalLayout_3.addWidget(self.lineEditTemp7)
        self.lineEditTemp8 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp8.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp8.setObjectName("lineEditTemp8")
        self.verticalLayout_3.addWidget(self.lineEditTemp8)
        self.lineEditTemp9 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp9.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp9.setObjectName("lineEditTemp9")
        self.verticalLayout_3.addWidget(self.lineEditTemp9)
        self.lineEditTemp10 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp10.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp10.setObjectName("lineEditTemp10")
        self.verticalLayout_3.addWidget(self.lineEditTemp10)
        self.lineEditTemp11 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp11.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp11.setObjectName("lineEditTemp11")
        self.verticalLayout_3.addWidget(self.lineEditTemp11)
        self.lineEditTemp12 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp12.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp12.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp12.setObjectName("lineEditTemp12")
        self.verticalLayout_3.addWidget(self.lineEditTemp12)
        self.lineEditTemp13 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp13.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp13.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp13.setObjectName("lineEditTemp13")
        self.verticalLayout_3.addWidget(self.lineEditTemp13)
        self.lineEditTemp14 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp14.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp14.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp14.setObjectName("lineEditTemp14")
        self.verticalLayout_3.addWidget(self.lineEditTemp14)
        self.lineEditTemp15 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp15.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp15.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp15.setObjectName("lineEditTemp15")
        self.verticalLayout_3.addWidget(self.lineEditTemp15)
        self.lineEditTemp16 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp16.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp16.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp16.setObjectName("lineEditTemp16")
        self.verticalLayout_3.addWidget(self.lineEditTemp16)
        self.lineEditTemp17 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp17.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp17.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp17.setObjectName("lineEditTemp17")
        self.verticalLayout_3.addWidget(self.lineEditTemp17)
        self.lineEditTemp18 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp18.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp18.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp18.setObjectName("lineEditTemp18")
        self.verticalLayout_3.addWidget(self.lineEditTemp18)
        self.lineEditTemp19 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp19.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp19.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp19.setObjectName("lineEditTemp19")
        self.verticalLayout_3.addWidget(self.lineEditTemp19)
        self.lineEditTemp20 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp20.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp20.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp20.setObjectName("lineEditTemp20")
        self.verticalLayout_3.addWidget(self.lineEditTemp20)
        self.lineEditTemp21 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp21.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp21.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp21.setObjectName("lineEditTemp21")
        self.verticalLayout_3.addWidget(self.lineEditTemp21)
        self.lineEditTemp22 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp22.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp22.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp22.setObjectName("lineEditTemp22")
        self.verticalLayout_3.addWidget(self.lineEditTemp22)
        self.lineEditTemp23 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp23.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp23.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp23.setObjectName("lineEditTemp23")
        self.verticalLayout_3.addWidget(self.lineEditTemp23)
        self.lineEditTemp24 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTemp24.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp24.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp24.setObjectName("lineEditTemp24")
        self.verticalLayout_3.addWidget(self.lineEditTemp24)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditTime1 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime1.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime1.setObjectName("lineEditTime1")
        self.verticalLayout.addWidget(self.lineEditTime1)
        self.lineEditTime2 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime2.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime2.setObjectName("lineEditTime2")
        self.verticalLayout.addWidget(self.lineEditTime2)
        self.lineEditTime3 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime3.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime3.setObjectName("lineEditTime3")
        self.verticalLayout.addWidget(self.lineEditTime3)
        self.lineEditTime4 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime4.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime4.setObjectName("lineEditTime4")
        self.verticalLayout.addWidget(self.lineEditTime4)
        self.lineEditTime5 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime5.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime5.setObjectName("lineEditTime5")
        self.verticalLayout.addWidget(self.lineEditTime5)
        self.lineEditTime6 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime6.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime6.setObjectName("lineEditTime6")
        self.verticalLayout.addWidget(self.lineEditTime6)
        self.lineEditTime7 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime7.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime7.setObjectName("lineEditTime7")
        self.verticalLayout.addWidget(self.lineEditTime7)
        self.lineEditTime8 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime8.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime8.setObjectName("lineEditTime8")
        self.verticalLayout.addWidget(self.lineEditTime8)
        self.lineEditTime9 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime9.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime9.setObjectName("lineEditTime9")
        self.verticalLayout.addWidget(self.lineEditTime9)
        self.lineEditTime10 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime10.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime10.setObjectName("lineEditTime10")
        self.verticalLayout.addWidget(self.lineEditTime10)
        self.lineEditTime11 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime11.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime11.setObjectName("lineEditTime11")
        self.verticalLayout.addWidget(self.lineEditTime11)
        self.lineEditTime12 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime12.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime12.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime12.setObjectName("lineEditTime12")
        self.verticalLayout.addWidget(self.lineEditTime12)
        self.lineEditTime13 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime13.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime13.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime13.setObjectName("lineEditTime13")
        self.verticalLayout.addWidget(self.lineEditTime13)
        self.lineEditTime14 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime14.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime14.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime14.setObjectName("lineEditTime14")
        self.verticalLayout.addWidget(self.lineEditTime14)
        self.lineEditTime15 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime15.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime15.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime15.setObjectName("lineEditTime15")
        self.verticalLayout.addWidget(self.lineEditTime15)
        self.lineEditTime16 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime16.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime16.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime16.setObjectName("lineEditTime16")
        self.verticalLayout.addWidget(self.lineEditTime16)
        self.lineEditTime17 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime17.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime17.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime17.setObjectName("lineEditTime17")
        self.verticalLayout.addWidget(self.lineEditTime17)
        self.lineEditTime18 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime18.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime18.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime18.setObjectName("lineEditTime18")
        self.verticalLayout.addWidget(self.lineEditTime18)
        self.lineEditTime19 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime19.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime19.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime19.setObjectName("lineEditTime19")
        self.verticalLayout.addWidget(self.lineEditTime19)
        self.lineEditTime20 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime20.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime20.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime20.setObjectName("lineEditTime20")
        self.verticalLayout.addWidget(self.lineEditTime20)
        self.lineEditTime21 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime21.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime21.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime21.setObjectName("lineEditTime21")
        self.verticalLayout.addWidget(self.lineEditTime21)
        self.lineEditTime22 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime22.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime22.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime22.setObjectName("lineEditTime22")
        self.verticalLayout.addWidget(self.lineEditTime22)
        self.lineEditTime23 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime23.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime23.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime23.setObjectName("lineEditTime23")
        self.verticalLayout.addWidget(self.lineEditTime23)
        self.lineEditTime24 = QtWidgets.QLineEdit(self.widget)
        self.lineEditTime24.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime24.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime24.setObjectName("lineEditTime24")
        self.verticalLayout.addWidget(self.lineEditTime24)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.MplWidgetGraphEditor = MplWidget(self.widget)
        self.MplWidgetGraphEditor.setMinimumSize(QtCore.QSize(620, 651))
        self.MplWidgetGraphEditor.setObjectName("MplWidgetGraphEditor")
        self.horizontalLayout_4.addWidget(self.MplWidgetGraphEditor)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Graph_editor)
        QtCore.QMetaObject.connectSlotsByName(Graph_editor)
        Graph_editor.setTabOrder(self.lineEditTemp1, self.lineEditTime1)
        Graph_editor.setTabOrder(self.lineEditTime1, self.lineEditTemp2)
        Graph_editor.setTabOrder(self.lineEditTemp2, self.lineEditTime2)
        Graph_editor.setTabOrder(self.lineEditTime2, self.lineEditTemp3)
        Graph_editor.setTabOrder(self.lineEditTemp3, self.lineEditTime3)
        Graph_editor.setTabOrder(self.lineEditTime3, self.lineEditTemp4)
        Graph_editor.setTabOrder(self.lineEditTemp4, self.lineEditTime4)
        Graph_editor.setTabOrder(self.lineEditTime4, self.lineEditTemp5)
        Graph_editor.setTabOrder(self.lineEditTemp5, self.lineEditTime5)
        Graph_editor.setTabOrder(self.lineEditTime5, self.lineEditTemp6)
        Graph_editor.setTabOrder(self.lineEditTemp6, self.lineEditTime6)
        Graph_editor.setTabOrder(self.lineEditTime6, self.lineEditTemp7)
        Graph_editor.setTabOrder(self.lineEditTemp7, self.lineEditTime7)
        Graph_editor.setTabOrder(self.lineEditTime7, self.lineEditTemp8)
        Graph_editor.setTabOrder(self.lineEditTemp8, self.lineEditTime8)
        Graph_editor.setTabOrder(self.lineEditTime8, self.lineEditTemp9)
        Graph_editor.setTabOrder(self.lineEditTemp9, self.lineEditTime9)
        Graph_editor.setTabOrder(self.lineEditTime9, self.lineEditTemp10)
        Graph_editor.setTabOrder(self.lineEditTemp10, self.lineEditTime10)
        Graph_editor.setTabOrder(self.lineEditTime10, self.lineEditTemp11)
        Graph_editor.setTabOrder(self.lineEditTemp11, self.lineEditTime11)
        Graph_editor.setTabOrder(self.lineEditTime11, self.lineEditTemp12)
        Graph_editor.setTabOrder(self.lineEditTemp12, self.lineEditTime12)
        Graph_editor.setTabOrder(self.lineEditTime12, self.lineEditTemp13)
        Graph_editor.setTabOrder(self.lineEditTemp13, self.lineEditTime13)
        Graph_editor.setTabOrder(self.lineEditTime13, self.lineEditTemp14)
        Graph_editor.setTabOrder(self.lineEditTemp14, self.lineEditTime14)
        Graph_editor.setTabOrder(self.lineEditTime14, self.lineEditTemp15)
        Graph_editor.setTabOrder(self.lineEditTemp15, self.lineEditTime15)
        Graph_editor.setTabOrder(self.lineEditTime15, self.lineEditTemp16)
        Graph_editor.setTabOrder(self.lineEditTemp16, self.lineEditTime16)
        Graph_editor.setTabOrder(self.lineEditTime16, self.lineEditTemp17)
        Graph_editor.setTabOrder(self.lineEditTemp17, self.lineEditTime17)
        Graph_editor.setTabOrder(self.lineEditTime17, self.lineEditTemp18)
        Graph_editor.setTabOrder(self.lineEditTemp18, self.lineEditTime18)
        Graph_editor.setTabOrder(self.lineEditTime18, self.lineEditTemp19)
        Graph_editor.setTabOrder(self.lineEditTemp19, self.lineEditTime19)
        Graph_editor.setTabOrder(self.lineEditTime19, self.lineEditTemp20)
        Graph_editor.setTabOrder(self.lineEditTemp20, self.lineEditTime20)
        Graph_editor.setTabOrder(self.lineEditTime20, self.lineEditTemp21)
        Graph_editor.setTabOrder(self.lineEditTemp21, self.lineEditTime21)
        Graph_editor.setTabOrder(self.lineEditTime21, self.lineEditTemp22)
        Graph_editor.setTabOrder(self.lineEditTemp22, self.lineEditTime22)
        Graph_editor.setTabOrder(self.lineEditTime22, self.lineEditTemp23)
        Graph_editor.setTabOrder(self.lineEditTemp23, self.lineEditTime23)
        Graph_editor.setTabOrder(self.lineEditTime23, self.lineEditTemp24)
        Graph_editor.setTabOrder(self.lineEditTemp24, self.lineEditTime24)

    def retranslateUi(self, Graph_editor):
        _translate = QtCore.QCoreApplication.translate
        Graph_editor.setWindowTitle(_translate("Graph_editor", "Редактор опорных графиков"))
        self.label.setText(_translate("Graph_editor", "Контрольные точки"))
        self.label_2.setText(_translate("Graph_editor", "Контрольный график"))
        self.comboBoxOwen.setItemText(0, _translate("Graph_editor", "Печь 1"))
        self.comboBoxOwen.setItemText(1, _translate("Graph_editor", "Печь 2"))
        self.comboBoxOwen.setItemText(2, _translate("Graph_editor", "Печь 3"))
        self.comboBoxOwen.setItemText(3, _translate("Graph_editor", "Печь 4"))
        self.comboBoxOwen.setItemText(4, _translate("Graph_editor", "Печь 5"))
        self.comboBoxOwen.setItemText(5, _translate("Graph_editor", "Печь 6"))
        self.comboBoxOwen.setItemText(6, _translate("Graph_editor", "Печь 7"))
        self.comboBoxOwen.setItemText(7, _translate("Graph_editor", "Печь 8"))
        self.comboBoxOwen.setItemText(8, _translate("Graph_editor", "Печь 9"))
        self.comboBoxOwen.setItemText(9, _translate("Graph_editor", "Печь 10"))
        self.label_15.setText(_translate("Graph_editor", "Темп, °С"))
        self.label_14.setText(_translate("Graph_editor", "Время, ч"))
        self.label_3.setText(_translate("Graph_editor", "1."))
        self.label_4.setText(_translate("Graph_editor", "2."))
        self.label_5.setText(_translate("Graph_editor", "3."))
        self.label_6.setText(_translate("Graph_editor", "4."))
        self.label_7.setText(_translate("Graph_editor", "5."))
        self.label_8.setText(_translate("Graph_editor", "6."))
        self.label_9.setText(_translate("Graph_editor", "7."))
        self.label_10.setText(_translate("Graph_editor", "8."))
        self.label_11.setText(_translate("Graph_editor", "9."))
        self.label_12.setText(_translate("Graph_editor", "10."))
        self.label_13.setText(_translate("Graph_editor", "11."))
        self.label_27.setText(_translate("Graph_editor", "12."))
        self.label_16.setText(_translate("Graph_editor", "13."))
        self.label_17.setText(_translate("Graph_editor", "14."))
        self.label_18.setText(_translate("Graph_editor", "15."))
        self.label_19.setText(_translate("Graph_editor", "16."))
        self.label_20.setText(_translate("Graph_editor", "17."))
        self.label_21.setText(_translate("Graph_editor", "18."))
        self.label_22.setText(_translate("Graph_editor", "19."))
        self.label_23.setText(_translate("Graph_editor", "20."))
        self.label_24.setText(_translate("Graph_editor", "21."))
        self.label_25.setText(_translate("Graph_editor", "22."))
        self.label_26.setText(_translate("Graph_editor", "23."))
        self.label_28.setText(_translate("Graph_editor", "24."))

from mplwidget import MplWidget
