# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Graph_editor(object):
    def setupUi(self, Graph_editor):
        Graph_editor.setObjectName("Graph_editor")
        Graph_editor.resize(474, 379)
        Graph_editor.setMaximumSize(QtCore.QSize(474, 379))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lines.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        Graph_editor.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Graph_editor)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 460, 364))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.lineEditTemp1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp1.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp1.setObjectName("lineEditTemp1")
        self.verticalLayout_2.addWidget(self.lineEditTemp1)
        self.lineEditTemp2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp2.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp2.setObjectName("lineEditTemp2")
        self.verticalLayout_2.addWidget(self.lineEditTemp2)
        self.lineEditTemp3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp3.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp3.setObjectName("lineEditTemp3")
        self.verticalLayout_2.addWidget(self.lineEditTemp3)
        self.lineEditTemp4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp4.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp4.setObjectName("lineEditTemp4")
        self.verticalLayout_2.addWidget(self.lineEditTemp4)
        self.lineEditTemp5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp5.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp5.setObjectName("lineEditTemp5")
        self.verticalLayout_2.addWidget(self.lineEditTemp5)
        self.lineEditTemp6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp6.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp6.setObjectName("lineEditTemp6")
        self.verticalLayout_2.addWidget(self.lineEditTemp6)
        self.lineEditTemp7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp7.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp7.setObjectName("lineEditTemp7")
        self.verticalLayout_2.addWidget(self.lineEditTemp7)
        self.lineEditTemp8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp8.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp8.setObjectName("lineEditTemp8")
        self.verticalLayout_2.addWidget(self.lineEditTemp8)
        self.lineEditTemp9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp9.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp9.setObjectName("lineEditTemp9")
        self.verticalLayout_2.addWidget(self.lineEditTemp9)
        self.lineEditTemp10 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp10.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp10.setObjectName("lineEditTemp10")
        self.verticalLayout_2.addWidget(self.lineEditTemp10)
        self.lineEditTemp11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTemp11.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTemp11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTemp11.setObjectName("lineEditTemp11")
        self.verticalLayout_2.addWidget(self.lineEditTemp11)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.lineEditTime1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime1.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime1.setObjectName("lineEditTime1")
        self.verticalLayout_3.addWidget(self.lineEditTime1)
        self.lineEditTime2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime2.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime2.setObjectName("lineEditTime2")
        self.verticalLayout_3.addWidget(self.lineEditTime2)
        self.lineEditTime3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime3.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime3.setObjectName("lineEditTime3")
        self.verticalLayout_3.addWidget(self.lineEditTime3)
        self.lineEditTime4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime4.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime4.setObjectName("lineEditTime4")
        self.verticalLayout_3.addWidget(self.lineEditTime4)
        self.lineEditTime5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime5.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime5.setObjectName("lineEditTime5")
        self.verticalLayout_3.addWidget(self.lineEditTime5)
        self.lineEditTime6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime6.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime6.setObjectName("lineEditTime6")
        self.verticalLayout_3.addWidget(self.lineEditTime6)
        self.lineEditTime7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime7.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime7.setObjectName("lineEditTime7")
        self.verticalLayout_3.addWidget(self.lineEditTime7)
        self.lineEditTime8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime8.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime8.setObjectName("lineEditTime8")
        self.verticalLayout_3.addWidget(self.lineEditTime8)
        self.lineEditTime9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime9.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime9.setObjectName("lineEditTime9")
        self.verticalLayout_3.addWidget(self.lineEditTime9)
        self.lineEditTime10 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime10.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime10.setObjectName("lineEditTime10")
        self.verticalLayout_3.addWidget(self.lineEditTime10)
        self.lineEditTime11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditTime11.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEditTime11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEditTime11.setObjectName("lineEditTime11")
        self.verticalLayout_3.addWidget(self.lineEditTime11)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.MplWidgetGraphEditor = MplWidget(self.layoutWidget)
        self.MplWidgetGraphEditor.setMinimumSize(QtCore.QSize(271, 291))
        self.MplWidgetGraphEditor.setObjectName("MplWidgetGraphEditor")
        self.horizontalLayout.addWidget(self.MplWidgetGraphEditor)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Graph_editor)
        QtCore.QMetaObject.connectSlotsByName(Graph_editor)
        Graph_editor.setTabOrder(self.lineEditTemp1, self.lineEditTime1)
        Graph_editor.setTabOrder(self.lineEditTime1, self.lineEditTemp2)
        Graph_editor.setTabOrder(self.lineEditTemp2, self.lineEditTime2)
        Graph_editor.setTabOrder(self.lineEditTime2, self.lineEditTemp3)
        Graph_editor.setTabOrder(self.lineEditTemp3, self.lineEditTime3)
        Graph_editor.setTabOrder(self.lineEditTime3, self.lineEditTemp4)
        Graph_editor.setTabOrder(self.lineEditTemp4, self.lineEditTime4)
        Graph_editor.setTabOrder(self.lineEditTime4, self.lineEditTemp5)
        Graph_editor.setTabOrder(self.lineEditTemp5, self.lineEditTime5)
        Graph_editor.setTabOrder(self.lineEditTime5, self.lineEditTemp6)
        Graph_editor.setTabOrder(self.lineEditTemp6, self.lineEditTime6)
        Graph_editor.setTabOrder(self.lineEditTime6, self.lineEditTemp7)
        Graph_editor.setTabOrder(self.lineEditTemp7, self.lineEditTime7)
        Graph_editor.setTabOrder(self.lineEditTime7, self.lineEditTemp8)
        Graph_editor.setTabOrder(self.lineEditTemp8, self.lineEditTime8)
        Graph_editor.setTabOrder(self.lineEditTime8, self.lineEditTemp9)
        Graph_editor.setTabOrder(self.lineEditTemp9, self.lineEditTime9)
        Graph_editor.setTabOrder(self.lineEditTime9, self.lineEditTemp10)
        Graph_editor.setTabOrder(self.lineEditTemp10, self.lineEditTime10)
        Graph_editor.setTabOrder(self.lineEditTime10, self.lineEditTemp11)
        Graph_editor.setTabOrder(self.lineEditTemp11, self.lineEditTime11)

    def retranslateUi(self, Graph_editor):
        _translate = QtCore.QCoreApplication.translate
        Graph_editor.setWindowTitle(_translate("Graph_editor", "Редактор опорных графиков"))
        self.label.setText(_translate("Graph_editor", "Контрольные точки"))
        self.label_2.setText(_translate("Graph_editor", "Контрольный график"))
        self.label_3.setText(_translate("Graph_editor", "1."))
        self.label_4.setText(_translate("Graph_editor", "2."))
        self.label_5.setText(_translate("Graph_editor", "3."))
        self.label_6.setText(_translate("Graph_editor", "4."))
        self.label_7.setText(_translate("Graph_editor", "5."))
        self.label_8.setText(_translate("Graph_editor", "6."))
        self.label_9.setText(_translate("Graph_editor", "7."))
        self.label_10.setText(_translate("Graph_editor", "8."))
        self.label_11.setText(_translate("Graph_editor", "9."))
        self.label_12.setText(_translate("Graph_editor", "10."))
        self.label_13.setText(_translate("Graph_editor", "11."))
        self.label_15.setText(_translate("Graph_editor", "Темп, °С"))
        self.label_14.setText(_translate("Graph_editor", "Время, ч"))

from mplwidget import MplWidget
