# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Graph_editor(object):
    def setupUi(self, Graph_editor):
        Graph_editor.setObjectName("Graph_editor")
        Graph_editor.resize(474, 379)
        Graph_editor.setMaximumSize(QtCore.QSize(474, 379))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lines.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        Graph_editor.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Graph_editor)
        self.widget.setGeometry(QtCore.QRect(9, 9, 460, 364))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_2.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_2.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_2.addWidget(self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_10.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_2.addWidget(self.lineEdit_10)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_2.addWidget(self.lineEdit_11)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_3.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_3.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_14.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_3.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_3.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_16.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_3.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_17.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_17.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_3.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_18.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_18.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_3.addWidget(self.lineEdit_18)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_19.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_3.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_20.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_3.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_21.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_21.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_3.addWidget(self.lineEdit_21)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_22.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_22.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_3.addWidget(self.lineEdit_22)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.MplWidgetGraphEditor = MplWidget(self.widget)
        self.MplWidgetGraphEditor.setMinimumSize(QtCore.QSize(271, 291))
        self.MplWidgetGraphEditor.setObjectName("MplWidgetGraphEditor")
        self.horizontalLayout.addWidget(self.MplWidgetGraphEditor)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Graph_editor)
        QtCore.QMetaObject.connectSlotsByName(Graph_editor)
        Graph_editor.setTabOrder(self.lineEdit, self.lineEdit_12)
        Graph_editor.setTabOrder(self.lineEdit_12, self.lineEdit_2)
        Graph_editor.setTabOrder(self.lineEdit_2, self.lineEdit_13)
        Graph_editor.setTabOrder(self.lineEdit_13, self.lineEdit_3)
        Graph_editor.setTabOrder(self.lineEdit_3, self.lineEdit_14)
        Graph_editor.setTabOrder(self.lineEdit_14, self.lineEdit_4)
        Graph_editor.setTabOrder(self.lineEdit_4, self.lineEdit_15)
        Graph_editor.setTabOrder(self.lineEdit_15, self.lineEdit_5)
        Graph_editor.setTabOrder(self.lineEdit_5, self.lineEdit_16)
        Graph_editor.setTabOrder(self.lineEdit_16, self.lineEdit_6)
        Graph_editor.setTabOrder(self.lineEdit_6, self.lineEdit_17)
        Graph_editor.setTabOrder(self.lineEdit_17, self.lineEdit_7)
        Graph_editor.setTabOrder(self.lineEdit_7, self.lineEdit_18)
        Graph_editor.setTabOrder(self.lineEdit_18, self.lineEdit_8)
        Graph_editor.setTabOrder(self.lineEdit_8, self.lineEdit_19)
        Graph_editor.setTabOrder(self.lineEdit_19, self.lineEdit_9)
        Graph_editor.setTabOrder(self.lineEdit_9, self.lineEdit_20)
        Graph_editor.setTabOrder(self.lineEdit_20, self.lineEdit_10)
        Graph_editor.setTabOrder(self.lineEdit_10, self.lineEdit_21)
        Graph_editor.setTabOrder(self.lineEdit_21, self.lineEdit_11)
        Graph_editor.setTabOrder(self.lineEdit_11, self.lineEdit_22)

    def retranslateUi(self, Graph_editor):
        _translate = QtCore.QCoreApplication.translate
        Graph_editor.setWindowTitle(_translate("Graph_editor", "Редактор опорных графиков"))
        self.label.setText(_translate("Graph_editor", "Контрольные точки"))
        self.label_2.setText(_translate("Graph_editor", "Контрольный график"))
        self.label_3.setText(_translate("Graph_editor", "1."))
        self.label_4.setText(_translate("Graph_editor", "2."))
        self.label_5.setText(_translate("Graph_editor", "3."))
        self.label_6.setText(_translate("Graph_editor", "4."))
        self.label_7.setText(_translate("Graph_editor", "5."))
        self.label_8.setText(_translate("Graph_editor", "6."))
        self.label_9.setText(_translate("Graph_editor", "7."))
        self.label_10.setText(_translate("Graph_editor", "8."))
        self.label_11.setText(_translate("Graph_editor", "9."))
        self.label_12.setText(_translate("Graph_editor", "10."))
        self.label_13.setText(_translate("Graph_editor", "11."))
        self.label_15.setText(_translate("Graph_editor", "Темп, °С"))
        self.label_14.setText(_translate("Graph_editor", "Время, ч"))

from mplwidget import MplWidget
