# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notification.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Notification(object):
    def setupUi(self, Notification):
        Notification.setObjectName("Notification")
        Notification.resize(245, 311)
        Notification.setMinimumSize(QtCore.QSize(245, 311))
        Notification.setMaximumSize(QtCore.QSize(245, 311))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lines.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Notification.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Notification)
        self.widget.setGeometry(QtCore.QRect(9, 9, 228, 296))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.NumbersLabel = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NumbersLabel.setFont(font)
        self.NumbersLabel.setObjectName("NumbersLabel")
        self.gridLayout.addWidget(self.NumbersLabel, 0, 0, 1, 1)
        self.Number1 = QtWidgets.QLineEdit(self.groupBox)
        self.Number1.setClearButtonEnabled(True)
        self.Number1.setObjectName("Number1")
        self.gridLayout.addWidget(self.Number1, 1, 0, 1, 1)
        self.Number2 = QtWidgets.QLineEdit(self.groupBox)
        self.Number2.setAutoFillBackground(False)
        self.Number2.setClearButtonEnabled(True)
        self.Number2.setObjectName("Number2")
        self.gridLayout.addWidget(self.Number2, 2, 0, 1, 1)
        self.Number3 = QtWidgets.QLineEdit(self.groupBox)
        self.Number3.setClearButtonEnabled(True)
        self.Number3.setObjectName("Number3")
        self.gridLayout.addWidget(self.Number3, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BalanceLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BalanceLabel.setFont(font)
        self.BalanceLabel.setObjectName("BalanceLabel")
        self.gridLayout_2.addWidget(self.BalanceLabel, 0, 0, 1, 1)
        self.BalanceCount = QtWidgets.QLabel(self.groupBox_2)
        self.BalanceCount.setObjectName("BalanceCount")
        self.gridLayout_2.addWidget(self.BalanceCount, 0, 1, 1, 1)
        self.LoginNameLabel = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LoginNameLabel.setFont(font)
        self.LoginNameLabel.setObjectName("LoginNameLabel")
        self.gridLayout_2.addWidget(self.LoginNameLabel, 1, 0, 1, 1)
        self.LoginLabel = QtWidgets.QLineEdit(self.groupBox_2)
        self.LoginLabel.setToolTip("")
        self.LoginLabel.setObjectName("LoginLabel")
        self.gridLayout_2.addWidget(self.LoginLabel, 2, 0, 1, 1)
        self.PasswordNameLabel = QtWidgets.QLabel(self.groupBox_2)
        self.PasswordNameLabel.setObjectName("PasswordNameLabel")
        self.gridLayout_2.addWidget(self.PasswordNameLabel, 3, 0, 1, 1)
        self.PasswordLabel = QtWidgets.QLineEdit(self.groupBox_2)
        self.PasswordLabel.setFrame(True)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.gridLayout_2.addWidget(self.PasswordLabel, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Notification)
        QtCore.QMetaObject.connectSlotsByName(Notification)

    def retranslateUi(self, Notification):
        _translate = QtCore.QCoreApplication.translate
        Notification.setWindowTitle(_translate("Notification", "Уведомления"))
        self.groupBox.setTitle(_translate("Notification", "Настройки"))
        self.NumbersLabel.setText(_translate("Notification", "Номера для рассылки оповещений"))
        self.Number1.setToolTip(_translate("Notification", "Номер должен иметь формат 79999999999"))
        self.Number1.setPlaceholderText(_translate("Notification", "79998887766"))
        self.Number2.setToolTip(_translate("Notification", "Номер должен иметь формат 79999999999"))
        self.Number2.setPlaceholderText(_translate("Notification", "79998887766"))
        self.Number3.setToolTip(_translate("Notification", "Номер должен иметь формат 79999999999"))
        self.Number3.setPlaceholderText(_translate("Notification", "79998887766"))
        self.groupBox_2.setTitle(_translate("Notification", "Настройки аккаунта SMSC.RU"))
        self.BalanceLabel.setText(_translate("Notification", "Баланс:"))
        self.BalanceCount.setText(_translate("Notification", "0,0р"))
        self.LoginNameLabel.setText(_translate("Notification", "Логин"))
        self.LoginLabel.setPlaceholderText(_translate("Notification", "Введите логин"))
        self.PasswordNameLabel.setText(_translate("Notification", "Пароль"))
        self.PasswordLabel.setPlaceholderText(_translate("Notification", "пароль"))

