# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'port_parameters.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(214, 175)
        Form.setMinimumSize(QtCore.QSize(214, 175))
        Form.setMaximumSize(QtCore.QSize(214, 175))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lines.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 196, 154))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.owenName_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.owenName_comboBox.setObjectName("owenName_comboBox")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.owenName_comboBox.addItem("")
        self.verticalLayout.addWidget(self.owenName_comboBox)
        self.port_Name_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.port_Name_comboBox.setObjectName("port_Name_comboBox")
        self.verticalLayout.addWidget(self.port_Name_comboBox)
        self.speed_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.speed_comboBox.setObjectName("speed_comboBox")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.speed_comboBox.addItem("")
        self.verticalLayout.addWidget(self.speed_comboBox)
        self.parity_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.parity_comboBox.setObjectName("parity_comboBox")
        self.parity_comboBox.addItem("")
        self.parity_comboBox.addItem("")
        self.parity_comboBox.addItem("")
        self.verticalLayout.addWidget(self.parity_comboBox)
        self.bits_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.bits_comboBox.setObjectName("bits_comboBox")
        self.bits_comboBox.addItem("")
        self.bits_comboBox.addItem("")
        self.verticalLayout.addWidget(self.bits_comboBox)
        self.stop_bits_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.stop_bits_comboBox.setObjectName("stop_bits_comboBox")
        self.stop_bits_comboBox.addItem("")
        self.stop_bits_comboBox.addItem("")
        self.verticalLayout.addWidget(self.stop_bits_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки портов"))
        self.label_6.setText(_translate("Form", "Печь"))
        self.label.setText(_translate("Form", "Порт:"))
        self.label_2.setText(_translate("Form", "Скорость:"))
        self.label_3.setText(_translate("Form", "Четность:"))
        self.label_4.setText(_translate("Form", "Кол-во бит:"))
        self.label_5.setText(_translate("Form", "Стоп бит:"))
        self.owenName_comboBox.setItemText(0, _translate("Form", "Печь 1"))
        self.owenName_comboBox.setItemText(1, _translate("Form", "Печь 2"))
        self.owenName_comboBox.setItemText(2, _translate("Form", "Печь 3"))
        self.owenName_comboBox.setItemText(3, _translate("Form", "Печь 4"))
        self.owenName_comboBox.setItemText(4, _translate("Form", "Печь 5"))
        self.owenName_comboBox.setItemText(5, _translate("Form", "Печь 6"))
        self.owenName_comboBox.setItemText(6, _translate("Form", "Печь 7"))
        self.owenName_comboBox.setItemText(7, _translate("Form", "Печь 8"))
        self.owenName_comboBox.setItemText(8, _translate("Form", "Печь 9"))
        self.owenName_comboBox.setItemText(9, _translate("Form", "Печь 10"))
        self.speed_comboBox.setItemText(0, _translate("Form", "1200"))
        self.speed_comboBox.setItemText(1, _translate("Form", "2400"))
        self.speed_comboBox.setItemText(2, _translate("Form", "4800"))
        self.speed_comboBox.setItemText(3, _translate("Form", "7200"))
        self.speed_comboBox.setItemText(4, _translate("Form", "9600"))
        self.speed_comboBox.setItemText(5, _translate("Form", "14400"))
        self.speed_comboBox.setItemText(6, _translate("Form", "19200"))
        self.speed_comboBox.setItemText(7, _translate("Form", "38400"))
        self.speed_comboBox.setItemText(8, _translate("Form", "57600"))
        self.speed_comboBox.setItemText(9, _translate("Form", "115200"))
        self.parity_comboBox.setItemText(0, _translate("Form", "Нет"))
        self.parity_comboBox.setItemText(1, _translate("Form", "Четный"))
        self.parity_comboBox.setItemText(2, _translate("Form", "Не четный"))
        self.bits_comboBox.setItemText(0, _translate("Form", "7"))
        self.bits_comboBox.setItemText(1, _translate("Form", "8"))
        self.stop_bits_comboBox.setItemText(0, _translate("Form", "1"))
        self.stop_bits_comboBox.setItemText(1, _translate("Form", "2"))

