# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Report(object):
    def setupUi(self, Report):
        Report.setObjectName("Report")
        Report.resize(730, 782)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("lines.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        Report.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Report)
        self.widget.setGeometry(QtCore.QRect(10, 13, 712, 713))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.filesDialog = QtWidgets.QPushButton(self.widget)
        self.filesDialog.setMaximumSize(QtCore.QSize(16777215, 200))
        self.filesDialog.setObjectName("filesDialog")
        self.horizontalLayout.addWidget(self.filesDialog)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.MplWidget = MplWidget(self.widget)
        self.MplWidget.setMinimumSize(QtCore.QSize(710, 639))
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout.addWidget(self.MplWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.moveLeftFast = QtWidgets.QPushButton(self.widget)
        self.moveLeftFast.setMinimumSize(QtCore.QSize(50, 0))
        self.moveLeftFast.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("fastleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveLeftFast.setIcon(icon1)
        self.moveLeftFast.setIconSize(QtCore.QSize(21, 23))
        self.moveLeftFast.setObjectName("moveLeftFast")
        self.horizontalLayout_2.addWidget(self.moveLeftFast)
        self.moveLeftSlow = QtWidgets.QPushButton(self.widget)
        self.moveLeftSlow.setMinimumSize(QtCore.QSize(50, 31))
        self.moveLeftSlow.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("slowleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveLeftSlow.setIcon(icon2)
        self.moveLeftSlow.setObjectName("moveLeftSlow")
        self.horizontalLayout_2.addWidget(self.moveLeftSlow)
        self.moveRightSlow = QtWidgets.QPushButton(self.widget)
        self.moveRightSlow.setMinimumSize(QtCore.QSize(50, 31))
        self.moveRightSlow.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("slowright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveRightSlow.setIcon(icon3)
        self.moveRightSlow.setObjectName("moveRightSlow")
        self.horizontalLayout_2.addWidget(self.moveRightSlow)
        self.moveRightFast = QtWidgets.QPushButton(self.widget)
        self.moveRightFast.setMinimumSize(QtCore.QSize(50, 0))
        self.moveRightFast.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("fastright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.moveRightFast.setIcon(icon4)
        self.moveRightFast.setIconSize(QtCore.QSize(21, 23))
        self.moveRightFast.setObjectName("moveRightFast")
        self.horizontalLayout_2.addWidget(self.moveRightFast)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Report)
        QtCore.QMetaObject.connectSlotsByName(Report)

    def retranslateUi(self, Report):
        _translate = QtCore.QCoreApplication.translate
        Report.setWindowTitle(_translate("Report", "Отчет"))
        self.label.setText(_translate("Report", "Выберите файлы для добавления их к отчету"))
        self.filesDialog.setText(_translate("Report", "Выбрать файлы"))

from mplwidget import MplWidget
